### ISSUE TITLE
Github Action + EC2 배포

### ISSUE THREAD

**Issue by youngdong82** [dongne-hanpan/FE#72]
I just follow this YouTube video.... and it works!✨

[Deploy react-app on EC2 instance using github actions | Pipeline | CI/CD](https://www.youtube.com/watch?v=0Kn6mAYIRJU)

**Comment by youngdong82** [comment]
왜 닫힌거지??

**Comment by youngdong82** [comment]
### Error 1. Process completed with exit code 1. when Run npm run build --if-present

**Error message:** 

```
Creating an optimized production build...

Treating warnings as errors because process.env.CI = true.
Most CI servers set it automatically.

Failed to compile.
```

Try Solution 1, 2. [:ref](https://stackoverflow.com/questions/62663451/treating-warnings-as-errors-because-process-env-ci-true-failed-to-compile)

> Add cod in node.js.yml file
```
env: 
  CI: false
```


> Edit build script in package.json
```
  "scripts": {
    "start": "react-scripts start",
    "build": "CI=false && react-scripts build",  // Add CI=False here
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
```

Try Solution 3. [:ref](https://www.youtube.com/watch?v=0Kn6mAYIRJU)

> Replace npm ci to npm install


### ---------------------------------------------------------------------------  _**Solved** with Solution 1_

**Comment by youngdong82** [comment]
[생활코딩 github action 강의](https://www.youtube.com/watch?v=uBOdEEzjxzE)

**Comment by Moveuk** [comment]
오... 멋있는데요~~

**Comment by youngdong82** [comment]
누군지 했는데 Move 욱 님...ㅋㅋㅋㅋㅋㅋ

**Comment by youngdong82** [comment]
[+jest?](https://www.youtube.com/watch?v=JUKZVlIDrtY)
